### ISSUE TITLE
Cannot find module 'adonis-fold'

### ISSUE THREAD

**Issue by jgardner04** [allanfreitas/adonis-mongorito#11]
After installing the adonis-mongorito module and adding `adonis-mongorito/providers/MongoritoProvider` to the app.js file I am getting the following error:

```
{ Error: Cannot find module 'adonis-fold'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jgardner/Git/CouchWalrus/src/couchWalrus/node_modules/adonis-mongorito/providers/MongoritoProvider.js:3:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by NicoG11** [comment]
In the changelog 0.2.0 the adonis-fold dependencies was removed.
So i think you have to manually include the dependencies...

> Remove adonis-fold from the dependencies. All packages should be dependent upon the adonis-fold version installed by the user app (can explain more if required).

For my adonis project, i switched to [Lucid-Mongo](https://github.com/duyluonglc/lucid-mongo)

**Comment by allanfreitas** [comment]
@NicoG11 @jgardner04 

I recomend the use of [Lucid-Mongo](https://github.com/duyluonglc/lucid-mongo) like @NicoG11 is using on his projects.

I'm working with many projects using Laravel and React these days, and I cannot invest time to give maintenance on this package right now.

But fell free to fix issues or improve it and make a pull request.

I will merge and publish the package as soon as possible(about 24h max)

**Comment by jgardner04** [comment]
@allanfreitas Thanks for the update. I totally get it. 

I have installed the Lucid-Mongo package and got it working as you recommended. Thanks!
